spring.application.name=gci-api
######################################
## Databases source Docker conteinar #
######################################
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gestor_carteira}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:carteira}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:carteira}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
server.port=8080
#####################################
## HG BRASIL API                    #
#####################################
hgbrasil.api.url=https://api.hgbrasil.com
hgbrasil.api.key=${HG_BRASIL_API_KEY}
######################################
## Databases source localhost        #
######################################
#spring.datasource.url=jdbc:mysql://localhost:3306/gestor_carteira
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#server.port=8080

